# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
 schedule:
   - cron: '0 8 * * *'
 workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up git config
        run: |
           git config user.name "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: | 
          git remote add upstream https://github.com/liquidslr/leetcode-company-wise-problems.git
          git fetch upstream

      - name: Add upstream remote
        run: | 
          git checkout main
          git merge upstream/main

      - name: Push changes to fork
        run: | 
          git push origin main

